version: '3.12'

services:
    web:
        build: .
        command:
            bash -c "python manage.py migrate &&
                    python manage.py runserver 0.0.0.0:8000"
        ports:
            - "8000:8000"
        env_file:
            - .env
        volumes:
            - .:/code
        depends_on:
            - db
            - redis
        networks:
            - app_network

    nginx:
        build:
            context: ./nginx
        ports:
            - "80:80"
            - "443:443"
        volumes:
            - ./nginx/nginx.conf:/etc/nginx/nginx.conf
            - static_volume:/app/staticfiles
        depends_on:
            - web

    db:
        image: postgres:16
        container_name: postgres_db1
        env_file:
            - ./.env
        ports:
          - "5432:5432"
        volumes:
            - postgres_data:/var/lib/postgresql/data
        networks:
            - app_network
    redis:
        image: redis:7
        container_name: redis1
        ports:
            - "6379:6379"
        env_file:
            - ./.env
        volumes:
            - redis_data:/data
    celery:
        build:
            context: .
        container_name: celery_worker1
        command:
            celery -A config worker -l INFO
        env_file:
            - .env
        volumes:
            - .:/app1
        depends_on:
            - db
            - redis

    celery_beat:
        build:
            context: .
        container_name: celery_beat1
        command:
            celery -A config beat --loglevel=INFO
        env_file:
            - .env
        volumes:
            - .:/app1
        depends_on:
            - db
            - redis
            - celery
networks:
    app_network:
        driver: bridge
volumes:
    postgres_data:
    redis_data: