version: '3.9'

services:
    web:
        build:
            context: .
            dockerfile: Dockerfile
        command:
            bash -c "python manage.py migrate &&
                    python manage.py runserver 0.0.0.0:8000"
        ports:
            - "8000:8000"
        env_file:
            - .env
        volumes:
            - .:/code
        depends_on:
            - db
            - redis
        networks:
            - app_network

    db:
        image: postgres:16
        container_name: postgres_db_habits
        environment:
            POSTGRES_DB: habits_tables
            POSTGRES_USER: postgres
            POSTGRES_PASSWORD: Al.krotov7
            POSTGRES_HOST: db
        ports:
          - "5432:5432"
        volumes:
            - postgres_data:/var/lib/postgresql/data
        networks:
            - app_network
    redis:
        image: redis:7
        container_name: redis_habits
        ports:
            - "6379:6379"
        env_file:
            - ./.env
        volumes:
            - redis_data:/data
    celery:
        build:
            context: .
        container_name: celery_worker_habits
        command:
            celery -A config worker -l INFO
        env_file:
            - .env
        volumes:
            - .:/app
        depends_on:
            - db
            - redis

    celery_beat:
        build:
            context: .
        container_name: celery_beat_habits
        command:
            celery -A config beat --loglevel=INFO
        env_file:
            - .env
        volumes:
            - .:/app
        depends_on:
            - db
            - redis
            - celery
networks:
    app_network:
        driver: bridge
volumes:
    postgres_data:
    redis_data: