# Generated by Django 5.2.4 on 2025-09-13 23:20

import datetime
import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Habit",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "place",
                    models.CharField(max_length=28, verbose_name="Место привычки"),
                ),
                (
                    "time",
                    models.TimeField(
                        blank=True,
                        null=True,
                        verbose_name="Время для начала выполнения привычки",
                    ),
                ),
                (
                    "action",
                    models.CharField(
                        max_length=100,
                        verbose_name="действие, которое представляет собой привычка",
                    ),
                ),
                (
                    "pleasure_habit",
                    models.BooleanField(
                        blank=True,
                        null=True,
                        verbose_name="Является ли привычка приятной",
                    ),
                ),
                (
                    "period",
                    models.PositiveSmallIntegerField(
                        blank=True,
                        default=1,
                        null=True,
                        validators=[django.core.validators.MaxValueValidator(7)],
                        verbose_name="Периодичность выполнения привычки",
                    ),
                ),
                (
                    "reward",
                    models.CharField(
                        blank=True,
                        max_length=100,
                        null=True,
                        verbose_name="Вознаграждение за выполнение привычки",
                    ),
                ),
                (
                    "time_to_complete",
                    models.DurationField(
                        blank=True,
                        default=datetime.timedelta(seconds=120),
                        null=True,
                        verbose_name="Время на выполение привычки",
                    ),
                ),
                (
                    "is_public",
                    models.BooleanField(
                        blank=True, null=True, verbose_name="Признак публичности"
                    ),
                ),
                (
                    "related_habit",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="habits.habit",
                        verbose_name="Связанная привычка",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Пользователь",
                    ),
                ),
            ],
            options={
                "verbose_name": "Привычка",
                "verbose_name_plural": "Привычки",
            },
        ),
    ]
